plugins {
    id 'java'
}

group 'Nyaacat'
version '1.6'

ext.minecraftVersion = "1.21.11"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

repositories {
    mavenCentral()
    maven { name 'papermc';     url 'https://repo.papermc.io/repository/maven-public/' }
    maven { name 'NyaaCat';     url 'https://ci.nyaacat.com/maven/' }
    maven { name 'aikar';     url 'https://repo.aikar.co/content/groups/aikar/' }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    implementation('cat.nyaa:nyaacore:9.10')
    compileOnly "io.papermc.paper:paper-api:${minecraftVersion}-R0.1-SNAPSHOT"
}

test {
    useJUnitPlatform()
}
