name: Saika
main: cat.nyaa.saika.Saika
description: "Random item craft utility for Nyaacat Minecraft Server"
version: v1.0
depend: [NyaaCore,LangUtils]
authors: [ReinWD]
website: "https://github.com/NyaaCat/Saika"
database: false
api-version: 1.13
commands:
  saika:
    description: Commands for Saika plugin
    permission: saika.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"
  saikal:
    description: Pool list Command for Saika plugin
    permission: saika.list
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"
permissions:
  saika.command:
    description: default command permission
    default: true
  saika.admin.add:
    description: add a forgeable item.
    default: op
  saika.admin.define:
    description: define a forge iron/element/enchant/repulse.
    default: op
  saika.admin.delete:
    description: delete a forge iron/element/enchant/repulse.
    default: op
  saika.admin.modify:
    description: modify a forge iron/element/enchant/repulse.
    default: op
  saika.admin.bonus:
    description: manage bonus items
    default: op
  saika.admin.remove:
    description: remove a forgeable item
    default: op
  saika.list:
    description: list pool information
    default: true

  saika.open:
    description: open a forge UI
    default: true